[package]
name = "git-clean"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
ezcli = "0.4.0"
futures = "0.3.24"
git2 = "0.15.0"
lazy_static = "1.4.0"
octocrab = "0.17.0"
regex = "1.6.0"
slog = { version = "2.7.0", features = ["max_level_trace"] }
slog-async = "2.7.0"
slog-term = "2.9.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
