[package]
name = "git-clean"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
color-eyre = "0.6.2"
dirs = "4.0.0"
futures = "0.3.26"
git2 = "0.16.1"
lazy_static = "1.4.0"
octocrab = "0.18.1"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
slog = "2.7.0"
slog-async = "2.7.0"
slog-term = "2.9.0"
smallstr = "0.3.0"
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.2"
